#!/bin/bash

echo "🔧 Hướng dẫn setup Firebase Storage"
echo ""
echo "⚠️  Firebase Storage chưa được enable!"
echo ""
echo "📋 Các bước cần thực hiện:"
echo ""
echo "1️⃣  Enable Firebase Storage:"
echo "   - Vào: https://console.firebase.google.com/project/applichcongtac/storage"
echo "   - Click 'Get Started'"
echo "   - Chọn location: asia-southeast1 (Singapore) hoặc asia-southeast2 (Jakarta)"
echo "   - Chọn 'Start in production mode' hoặc 'Start in test mode'"
echo ""
echo "2️⃣  Deploy Storage Rules:"
echo "   firebase deploy --only storage"
echo ""
echo "3️⃣  Cấu hình CORS (chọn 1 trong 2 cách):"
echo ""
echo "   Cách A - Qua Google Cloud Console (Khuyến nghị):"
echo "   - Vào: https://console.cloud.google.com/storage/browser?project=applichcongtac"
echo "   - Tìm bucket: applichcongtac.firebasestorage.app"
echo "   - Click vào bucket > Configuration tab > CORS"
echo "   - Click 'Edit CORS configuration'"
echo "   - Paste nội dung từ file cors.json"
echo "   - Click 'Save'"
echo ""
echo "   Cách B - Qua gsutil (nếu đã cài Google Cloud SDK):"
echo "   gsutil cors set cors.json gs://applichcongtac.firebasestorage.app"
echo ""
echo "4️⃣  Kiểm tra lại:"
echo "   - Clear browser cache"
echo "   - Hard refresh (Cmd+Shift+R)"
echo "   - Thử upload ảnh lại"
echo ""
